###############################################################
#         _            _ _                ____ _____ _   _    #
#   _ __ (_)_ __   ___| (_)_ __   ___    |  _ \_   _| | | |   #
#  | '_ \| | '_ \ / _ \ | | '_ \ / _ \   | | | || | | | | |   #
#  | |_) | | |_) |  __/ | | | | |  __/   | |_| || | | |_| |   #
#  | .__/|_| .__/ \___|_|_|_| |_|\___|___|____/ |_|  \___/    #
#  |_|     |_|                      |_____|                   #
#                                                             #
###############################################################

# the genome to use (UCSC convention)
genome: hg38_noalt

database:
    name: <shared_location>/DTUtrons/dtu_db
    url: sqlite:////<shared_location>/dtu_db

###############################################################
# Location of annotation database
###############################################################
annotations:
    database: /shared/sudlab1/General/annotations/hg38_noalt_ensembl85/csvdb

    # directory with annotation information
    dir: /shared/sudlab1/General/annotations/hg38_noalt_ensembl85


###############################################################
# Stringtie configuration
###############################################################

stringtie:
    #options for assembling with stringtie
    threads: 4
    options: -f 0.05
    memory: 12G

    merge_threads: 4
    merge_memory: 12G
    merge_options: -F 0 -T 1
    groups: []

    #options for quantifying with stringtie
    quant_threads: 2
    quant_memory: 6G
    quant_options: ''

gtf2table:
    classifier: classifier-rnaseq-splicing

###############################################################
# Portcullis configuration
###############################################################

portcullis:
    #Fasta reference 
    fastaref: /shared/sudlab1/General/mirror/genomes/plain/hg38.fasta
    # Reference of junctions in BED format
    bedref: /shared/sudlab1/General/Data/projects/utrons/GRCh38_gencode28_annotation.bed

    orientation: FR  
  
###############################################################
# Salmon configuration
###############################################################

salmon:
    # Options for building the salmon index
    indexoptions: -k 31
    # Options for quantifying samples
    quantoptions: --validateMappings --rangeFactorizationBins 4
    num_bootstraps: 100 

###############################################################
# DTU configuration
###############################################################

dtu: 
    #location of design matrix
    design_tsv_location: <shared_location>/DTU/design.tsv
    drim_dex_filters:
        #what transcript count do samples need to have to be used
        minimum_samples_tx_expression_cutoff: 10
        #what transcript proportion of gene (e.g. fractional expression) 
        #do these transcripts need to have
        minimum_samples_tx_proportion_cutoff: 0.1 
        #what proportion of samples does this criteria need to apply to
        minimum_samples_transcript_n: 0.4
        #e.g. expression = 10, proportion = 0.1, and n=0.4 means that 40% of samples
        #must have transcript count >10 and fract.expr>10%
         
        #what gene count do transcripts need to have to be used
        minimum_samples_gene_expression: 10
        #what proportion of samples does this criteria need to apply to
        minimum_samples_gene_n: 0.75
        #e.g. expression = 10 and n = 0.75 means that
        #75% of samples must have a gene expression > 10 for the
        #gene to be considered for DTU

    swish_settings:
        paired: FALSE